/**
 * Codex Runtime — internal types isolating us from upstream schema drift.
 *
 * Phase 5 Phase 1 (2026-05-13). Source of truth for the upstream
 * shapes lives in `资料/codex/codex-rs/app-server-protocol/schema/typescript/`
 * — those are generated by ts-rs from the Rust source and regenerated
 * on every Codex release. We never `import` those files into the
 * product; instead, this module defines the narrow subset CodePilot
 * actually consumes, plus a few helper unions and a typed RPC envelope.
 *
 * Adding fields: if a new Codex schema field becomes useful for the
 * adapter / UI, mirror it here AND add a contract test under
 * `__tests__/unit/codex-types.test.ts` that asserts the shape matches
 * the upstream schema file at the version we cloned.
 */

// ─────────────────────────────────────────────────────────────────────
// JSON-RPC envelope (2.0). app-server omits the `"jsonrpc":"2.0"` header
// on the wire, but our client still emits it — the server accepts both.
// ─────────────────────────────────────────────────────────────────────

export interface JsonRpcRequest<TParams = unknown> {
  jsonrpc?: '2.0';
  id: number | string;
  method: string;
  params?: TParams;
}

export interface JsonRpcNotification<TParams = unknown> {
  jsonrpc?: '2.0';
  method: string;
  params?: TParams;
}

export interface JsonRpcSuccessResponse<TResult = unknown> {
  jsonrpc?: '2.0';
  id: number | string;
  result: TResult;
}

export interface JsonRpcErrorResponse {
  jsonrpc?: '2.0';
  id: number | string | null;
  error: { code: number; message: string; data?: unknown };
}

export type JsonRpcResponse<TResult = unknown> =
  | JsonRpcSuccessResponse<TResult>
  | JsonRpcErrorResponse;

export type JsonRpcMessage =
  | JsonRpcRequest
  | JsonRpcNotification
  | JsonRpcResponse;

/**
 * Backpressure error code per app-server README ("Server overloaded;
 * retry later." with code -32001). Client treats it as retryable and
 * applies exponential backoff with jitter.
 */
export const JSON_RPC_OVERLOADED_CODE = -32001 as const;

// ─────────────────────────────────────────────────────────────────────
// Initialize handshake
// ─────────────────────────────────────────────────────────────────────

export interface CodexClientInfo {
  /**
   * Per app-server README: this is used to identify the client for the
   * OpenAI Compliance Logs Platform. CodePilot identifies as
   * `'codex_codepilot'` so future enterprise reporting can resolve us.
   */
  name: string;
  title?: string | null;
  version: string;
}

export interface CodexInitializeCapabilities {
  experimentalApi?: boolean;
  /** Exact method names to suppress for this connection. */
  optOutNotificationMethods?: readonly string[];
}

export interface CodexInitializeResponse {
  userAgent: string;
  /** Absolute path to the server's $CODEX_HOME directory. */
  codexHome: string;
  /** Platform family — typically `"unix"` or `"windows"`. */
  platformFamily: string;
  /** Operating system — typically `"macos"`, `"linux"`, or `"windows"`. */
  platformOs: string;
}

// ─────────────────────────────────────────────────────────────────────
// Account
//
// Upstream `Account = { "type": "apiKey" } | { "type": "chatgpt", email, planType } | { "type": "amazonBedrock" }`
// We surface it through a narrowed CodexAccountState that the UI
// understands without inspecting the upstream union directly.
// ─────────────────────────────────────────────────────────────────────

export type CodexAccountKind = 'apiKey' | 'chatgpt' | 'amazonBedrock';

export interface CodexAccount {
  type: CodexAccountKind;
  /** ChatGPT plan only: account email. */
  email?: string;
  /** ChatGPT plan only: plan identifier (e.g. `plus`, `pro`). */
  planType?: string;
}

export type CodexAccountState =
  | { kind: 'unknown' }
  | { kind: 'logged_out' }
  | { kind: 'logged_in'; account: CodexAccount };

// ─────────────────────────────────────────────────────────────────────
// Model
// ─────────────────────────────────────────────────────────────────────

export interface CodexModel {
  id: string;
  /** The wire model id Codex passes to upstream. Often equal to `id`. */
  model: string;
  displayName: string;
  description: string;
  hidden: boolean;
  isDefault: boolean;
  /** Reasoning effort options, ordered. */
  supportedReasoningEfforts: readonly string[];
  defaultReasoningEffort: string;
  /** Input modalities (e.g. 'text', 'image'). */
  inputModalities: readonly string[];
  /** Optional service tiers (free / pro / etc). */
  serviceTiers?: readonly string[];
}

// ─────────────────────────────────────────────────────────────────────
// Thread / turn lifecycle
// ─────────────────────────────────────────────────────────────────────

export interface CodexThreadStartParams {
  /** Working directory for the thread. */
  cwd?: string;
  /** Optional thread name for UI display. */
  name?: string;
}

export interface CodexThreadStartResponse {
  thread: { id: string; status?: string; ephemeral?: boolean };
}

export interface CodexTurnStartParams {
  threadId: string;
  /** User input — Codex `UserInput[]`. We pass text-only items today. */
  input: readonly { type: 'text'; text: string }[];
  cwd?: string;
  model?: string;
  effort?: string;
}

export interface CodexTurnStartResponse {
  turn: { id: string; threadId: string };
}

// ─────────────────────────────────────────────────────────────────────
// Notifications we listen for during a turn
// ─────────────────────────────────────────────────────────────────────

export interface CodexAgentMessageDelta {
  threadId: string;
  turnId: string;
  itemId: string;
  delta: string;
}

export interface CodexTurnCompletedNotification {
  threadId: string;
  turnId: string;
  status?: string;
  usage?: {
    inputTokens?: number;
    outputTokens?: number;
    /** Codex emits modelContextWindow inside turn-completed. */
    modelContextWindow?: number;
  };
}

// ─────────────────────────────────────────────────────────────────────
// App-server health / availability
// ─────────────────────────────────────────────────────────────────────

export type CodexAvailability =
  | { kind: 'unknown' }
  /** `codex` binary not found on PATH. */
  | { kind: 'not_installed' }
  /** Binary found, but the app-server has not been initialized in this process yet. */
  | { kind: 'installed_idle'; binary: string }
  /** Binary found but version is below our minimum supported. */
  | { kind: 'too_old'; version: string; minimum: string }
  /** Binary found and version OK, but spawn failed. */
  | { kind: 'spawn_failed'; reason: string }
  /** App-server initialized successfully. */
  | { kind: 'ready'; version: string; codexHome: string };

/**
 * Codex Compliance Logs name for this integration. Per app-server
 * README §Initialization: enterprise reporting routes by clientInfo.name.
 */
export const CODEX_CLIENT_NAME = 'codex_codepilot' as const;

// ─────────────────────────────────────────────────────────────────────
// Rate limits
//
// Mirror of upstream `v2/RateLimitSnapshot.ts` narrowed to what the
// CodePilot UI surfaces. Upstream only reports `usedPercent` + a reset
// timestamp per window (no absolute remaining tokens), so the UI text
// must read "剩余 X%" / "rolls over in Y", not "X tokens remaining".
//
// Phase 5 Phase 6 (2026-05-14) — adds the quota widget in Providers'
// virtual Codex Account card.
// ─────────────────────────────────────────────────────────────────────

export interface CodexRateLimitWindow {
  /** 0–100. UI displays as "已用 X%" / "剩余 (100−X)%". */
  usedPercent: number;
  /** Length of the rolling window in minutes (5h = 300, 7d = 10080). */
  windowDurationMins?: number;
  /** Epoch seconds when the window rolls over. UI renders as relative time. */
  resetsAt?: number;
}

export interface CodexRateLimitCredits {
  hasCredits: boolean;
  unlimited: boolean;
  /**
   * Upstream sends `balance` as a decimal string ("0.42"). We pass it
   * through unparsed because UI rendering decides locale + precision.
   */
  balance?: string;
}

export interface CodexRateLimitSnapshot {
  primary?: CodexRateLimitWindow;
  secondary?: CodexRateLimitWindow;
  credits?: CodexRateLimitCredits;
  /** From the snapshot itself; may differ from account.planType during plan changes. */
  planType?: string;
  /** Non-null when the user is currently rate-limited. */
  rateLimitReachedType?: string;
}
